# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: id-ID
title: Seluk Beluk
# email:
description: Seluk Beluk catatan yang tak terlalu penting.
# twitter_username: username
# github_username: username
minimal_mistakes_skin: default

# Images
teaser: https://source.unsplash.com/weekly/640x320/?beauty
og_image: https://source.unsplash.com/random/920x460/?writing
logo: https://source.unsplash.com/random/88x88/?notepad
#Search
search: true
search_provider: google
google:
 search_engine_id: "012409504556434517711:oxyvbv1u6ko"
 instant_search: true
comments:
 provider:
  utterances:
   theme: github-light
   issue_term: pathname

# SEO Related
google_site_verification : "KYQFq-wZMFvxDMR5G5rak58D-IwrgM8B_CuGS0To5AU"
bing_site_verification   : "DA3D4C0368D7AE1105218F7F5B5BD6AC"
alexa_site_verification  : "9vuxp7uDTuDQssajccQrFy1UnTQ"

# Analytics
analytics:
  provider               : "google-universal"
  google:
    tracking_id          : "UA-43841292-2"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Jakarta # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Idlohulhaq Nasyrih"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Pria kesepian yang kesulitan mendeskripsikan kegelisahan."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.paciran.com/author/mukidi"
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      url: "https://twitter.com/knoacc"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/idlohulhaq"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/lautansyair"

footer:
  links:
    - label: "Web"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://www.paciran.com/author/mukidi"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/lautansyair"
sass:
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local] # default: local
  blanklines: true
  profile: false
  startings: [html, head, body]

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
