# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
safe: False
lsi: False
username: knoacc
repo: catetan
branch: master
relative_source: ../catetan/
destination: _site/
production_url: https://my.gootech.my.id/
#source_url: https://github.com/knoacc/catetan/
url: https://my.gootech.my.id
baseurl: /
#CNAME: my.gootech.my.id
title: "MYGOOTECH"
subtitle: "Catetan dan Seluk Beluk"
masthead_title: "SeBel"
# email:
description: "Seluk Beluk catatan yang tak terlalu penting tentang Web Development, Distro Linux, Android OS, Security Vulnerabilities hingga club sepakbola Liverpool FC"
twitter_username: knoacc
# github_username: username
# minimal_mistakes_skin: default
# Social
#social:
# type: person
# name: Idlohulhaq Nasyrih
# links:
#  - https://www.twitter.com/knoacc
#  - https://www.facebook.com/nasyrih
#  - https://instagram.com/lautansyair
facebook:
 app_id: 720457594754641
 publisher: https://www.facebook.com/nasyrih
# Images
teaser: https://cdn.statically.io/img/my.gootech.my.id/assets/images/teaser.gif
image: https://cdn.statically.io/img/my.gootech.my.id/assets/images/catetan.gif
logo: https://cdn.statically.io/img/my.gootech.my.id/assets/images/photo45.gif
#Search
search: true
search_provider: google
google:
  search_engine_id: "012409504556434517711:oxyvbv1u6ko"
  instant_search: true
words_per_minute: 200
comments:
  provider: utterances
  utterances:
   theme: "github-light"
   issue_term: "pathname"
repository: knoacc/catetan
# SEO Related
google_site_verification: "fYYFFxxNEP5-9x_N0og0owVt8q6EGqmmIwOCMRvin0s"
bing_site_verification: "DA3D4C0368D7AE1105218F7F5B5BD6AC"
alexa_site_verification: "9vuxp7uDTuDQssajccQrFy1UnTQ"
naver_site_verification: "b9b1f6708a13353f75e5b5a50e744f76de6f9303"
# Analytics
analytics:
  provider               : "google-universal"
  google:
    tracking_id          : "UA-149607626-1"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
# Outputting
permalink: /:categories/:title/
paginate: 10
paginate_path: /page:num/
timezone: Asia/Jakarta

include:
  - _pages
  - _demystic

exclude:
  - Gemfile
  - Gemfile.lock
  - _draft
  - arsip
  - node_modules
  - vendor
  - .travis.yml
  - script.py
  - .git*
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - README.md

# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
#  - jekyll-include-cache

whitelist:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
#  - jekyll-include-cache

author:
  name   : "Mukidi"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Pria kesepian yang kesulitan mendeskripsikan kegelisahan."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.gootech.my.id/"
#   - label: "Twitter"
#     icon: "fab fa-fw fa-twitter-square"
#     url: "https://twitter.com/knoacc"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/nasyrih"
    - label: "Instagram"
      icon: "fab fa-fw fa-telegram"
      url: "https://instagram.com/phateholloway"

footer:
  links:
    - label: "Terms"
      title: "Terms and Condition"
      icon: "fas fa-fw fa-power-off"
      url: "/terms/"
    - label: "Privacy"
      title: "Privacy Policy"
      icon: "fas fa-fw fa-user-secret"
      url: "/privacy/"
    - label: "Disclaimer"
      title: "Disclaimer of SeBel"
      icon: "fas fa-fw fa-copyright"
      url: /disclaimer/
sass:
  style: compressed

collections:
  demystic:
    output: true
    permalink: "/demystifying-computers/:path/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
  # _demistyc
  - scope:
      path: ""
      type: demistyc
    values:
      layout: single
      author_profile: false
      share: true
  # arsip
#  - scope:
#      path: "arsip/*/*/"
#      type: pages
#    values:
#      layout: single
#      author_profile: false
#      read_time: true
#      comments: true
#      share: true

compress_html:
  clippings: all
  ignore:
    envs: development
category_archive:
  type: liquid
  path: /kategori/
tag_archive:
  type: liquid
  path: /tanda/
