# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
url: https://www.catetan.pw
title: Catetan SeBel
subtitle: Catetan dan Seluk Beluk
masthead_title: "SeBel"
# email:
description: Seluk Beluk catatan yang tak terlalu penting tentang Web Development, Distro Linux, Android OS, Security Vulnerabilities hingga club sepakbola Liverpool FC"
twitter_username: knoacc
# github_username: username
# minimal_mistakes_skin: default
# Social
social:
 type: person
 name: Idlohulhaq Nasyrih
 links:
  - https://www.twitter.com/knoacc
  - https://www.facebook.com/nasyrih
  - https://instagram.com/lautansyair
  - https://www.paciran.com/author/mukidi
facebook:
 app_id: 720457594754641
 publisher: https://www.facebook.com/pssi.vi
# Images
teaser: https://cdn.statically.io/img/www.catetan.pw/assets/images/teaser.gif
image: https://cdn.statically.io/img/www.catetan.pw/assets/images/catetan.gif
logo: https://cdn.statically.io/img/www.catetan.pw/assets/images/photo45.gif
#Search
search: true
search_provider: google
google:
  search_engine_id: "012409504556434517711:oxyvbv1u6ko"
  instant_search: true
words_per_minute: 200
comments:
  provider: utterances
  utterances:
   theme: "github-light"
   issue_term: "pathname"
repository: "knoacc/catetan"
# SEO Related
google_site_verification: "fYYFFxxNEP5-9x_N0og0owVt8q6EGqmmIwOCMRvin0s"
bing_site_verification: "DA3D4C0368D7AE1105218F7F5B5BD6AC"
alexa_site_verification: "9vuxp7uDTuDQssajccQrFy1UnTQ"
naver_site_verification: "b9b1f6708a13353f75e5b5a50e744f76de6f9303"
# Analytics
analytics:
  provider               : "google-universal"
  google:
    tracking_id          : "UA-149607626-1"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.17.2"
# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Jakarta

include:
  - _pages
  - _arsip
exclude:
  - Gemfile
  - Gemfile.lock
  - _draft
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
#  - jemoji
  - jekyll-include-cache

author:
  name   : "Idlohulhaq Nasyrih"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Pria kesepian yang kesulitan mendeskripsikan kegelisahan."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.paciran.com/author/mukidi"
#   - label: "Twitter"
#     icon: "fab fa-fw fa-twitter-square"
#     url: "https://twitter.com/knoacc"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/nasyrih"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/lautansyair"

footer:
  links:
    - label: "Terms"
      title: "Terms and Condition"
      icon: "fas fa-fw fa-power-off"
      url: "/terms/"
    - label: "Privacy"
      title: "Privacy Policy"
      icon: "fas fa-fw fa-user-secret"
      url: "/privacy/"
    - label: "Disclaimer"
      title: "Disclaimer of SeBel"
      icon: "fas fa-fw fa-copyright"
      url: /disclaimer/
sass:
  style: compressed
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
  # _arsip
  - scope:
      path: "_arsip"
      type: pages
    values:
      layout: single
      author_profile: false
      permalink: /arsip/:title/
compress_html:
  clippings: all
  ignore:
    envs: development
category_archive:
  type: liquid
  path: /kategori/
tag_archive:
  type: liquid
  path: /tanda/
